# Generated by Django 3.0.2 on 2020-02-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=15)),
                ('hours', models.ManyToManyField(blank=True, to='core.WorkHours')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='days',
            field=models.ManyToManyField(blank=True, to='core.WorkDay'),
        ),
    ]
