# Generated by Django 3.0.3 on 2020-02-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200219_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='end_hour',
            field=models.TimeField(default="16:00"),
        ),
        migrations.AddField(
            model_name='business',
            name='start_hour',
            field=models.TimeField(default="08:00"),
        ),
    ]
