# Generated by Django 3.0.3 on 2020-02-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200220_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='hours',
        ),
    ]
