# Generated by Django 3.0.3 on 2020-02-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_business_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
