# Generated by Django 3.0.3 on 2020-02-24 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20200224_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='name',
        ),
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL),
        ),
    ]
