# Generated by Django 3.0.3 on 2020-02-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200225_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointment',
        ),
    ]
