# Generated by Django 3.0.3 on 2020-02-25 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(default='')),
                ('time', models.TimeField(default='08:00')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='core.Business')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='core.Client')),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.TreatmentType')),
            ],
        ),
    ]
